drop table allotment;
drop table avail;
drop table contain;
drop table accounts;
drop table booking;
drop table food;
drop table invoice;
drop table stay;
drop table customer;
drop table room;
drop table shift;
alter table branch drop constraint gm_key;
drop table employee;
drop table branch;